{{- if .Values.quak.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bosun.componentFullname" (dict "root" . "component" "quak") }}-env
  namespace: {{ include "bosun.namespace" . }}
  labels:
    {{- include "bosun.labels" . | nindent 4 }}
    app.kubernetes.io/component: quak
{{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
data:
{{- if .Values.quak.env }}
{{- range $key, $value := .Values.quak.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- else }}
  {}
{{- end }}
{{- end }}
