{{- if .Values.quak.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bosun.componentFullname" (dict "root" . "component" "quak") }}-env
  namespace: {{ include "bosun.namespace" . }}
  labels:
    {{- include "bosun.labels" . | nindent 4 }}
    app.kubernetes.io/component: quak
{{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
data:
{{- $userEnv := .Values.quak.env | default dict }}
{{- $env := dict }}
{{- range $key, $value := $userEnv }}
{{- $_ := set $env $key $value }}
{{- end }}
{{- $redisShared := include "bosun.componentFullname" (dict "root" . "component" "redis-shared") }}
{{- $redisIndexing := include "bosun.componentFullname" (dict "root" . "component" "redis-indexing") }}
{{- $qdrantService := include "bosun.componentFullname" (dict "root" . "component" "qdrant") }}
{{- $_ := set $env "REDIS_URL" (default (printf "redis://%s:%d" $redisShared (int .Values.redis.shared.service.port)) (get $userEnv "REDIS_URL")) }}
{{- $_ := set $env "REDIS_INDEXING_URL" (default (printf "redis://%s:%d" $redisIndexing (int .Values.redis.indexing.service.port)) (get $userEnv "REDIS_INDEXING_URL")) }}
{{- $_ := set $env "QDRANT_URL" (default (printf "http://%s:%d" $qdrantService (int .Values.qdrant.service.grpcPort)) (get $userEnv "QDRANT_URL")) }}
{{- if eq .Values.scm.mode "gitlab" }}
{{- $_ := set $env "GITLAB_API_ENDPOINT" (default .Values.scm.gitlab.apiEndpoint (get $userEnv "GITLAB_API_ENDPOINT")) }}
{{- end }}
{{- if $env }}
{{- range $key, $value := $env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- else }}
  {}
{{- end }}
{{- end }}
