{{- if .Values.quak.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bosun.componentFullname" (dict "root" . "component" "quak") }}
  namespace: {{ include "bosun.namespace" . }}
  labels:
    {{- include "bosun.labels" . | nindent 4 }}
    app.kubernetes.io/component: quak
{{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.quak.replicas }}
  selector:
    matchLabels:
      {{- include "bosun.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: quak
  template:
    metadata:
      labels:
        {{- include "bosun.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: quak
{{- $podAnnotations := .Values.quak.podAnnotations | default dict }}
{{- if not $podAnnotations }}
{{- $podAnnotations = .Values.global.podAnnotations | default dict }}
{{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/quak/configmap.yaml") . | sha256sum }}
{{- with $podAnnotations }}
        {{- toYaml . | nindent 8 }}
{{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.quak.terminationGracePeriodSeconds }}
{{- $serviceAccountName := include "bosun.quak.serviceAccountName" . }}
{{- if $serviceAccountName }}
      serviceAccountName: {{ $serviceAccountName }}
{{- end }}
{{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
{{- range . }}
        - name: {{ . }}
{{- end }}
{{- end }}
{{- if .Values.quak.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.quak.nodeSelector | nindent 8 }}
{{- else if .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.global.nodeSelector | nindent 8 }}
{{- end }}
{{- if .Values.quak.tolerations }}
      tolerations:
        {{- toYaml .Values.quak.tolerations | nindent 8 }}
{{- else if .Values.global.tolerations }}
      tolerations:
        {{- toYaml .Values.global.tolerations | nindent 8 }}
{{- end }}
{{- if .Values.quak.affinity }}
      affinity:
        {{- toYaml .Values.quak.affinity | nindent 8 }}
{{- else if .Values.global.affinity }}
      affinity:
        {{- toYaml .Values.global.affinity | nindent 8 }}
{{- end }}
      containers:
        - name: quak
          image: "{{ .Values.quak.image.repository }}:{{ .Values.quak.image.tag }}"
          imagePullPolicy: {{ .Values.quak.image.pullPolicy }}
{{- with .Values.quak.command }}
          command:
            {{- toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.quak.args }}
          args:
            {{- toYaml . | nindent 12 }}
{{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "bosun.componentFullname" (dict "root" . "component" "quak") }}-env
{{- range .Values.quak.secrets.existing }}
            - secretRef:
                name: {{ . }}
{{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.quak.containerPort }}
              protocol: TCP
{{- with .Values.quak.probes.readiness }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.quak.probes.liveness }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.quak.probes.startup }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
{{- end }}
{{- if .Values.quak.resources }}
          resources:
            {{- toYaml .Values.quak.resources | nindent 12 }}
{{- else if .Values.global.resources }}
          resources:
            {{- toYaml .Values.global.resources | nindent 12 }}
{{- end }}
{{- end }}
