{{- if .Values.bow.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bosun.componentFullname" (dict "root" . "component" "bow") }}
  namespace: {{ include "bosun.namespace" . }}
  labels:
    {{- include "bosun.labels" . | nindent 4 }}
    app.kubernetes.io/component: bow
{{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.bow.replicas }}
  selector:
    matchLabels:
      {{- include "bosun.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: bow
  template:
    metadata:
      labels:
        {{- include "bosun.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: bow
{{- $podAnnotations := .Values.bow.podAnnotations | default dict }}
{{- if not $podAnnotations }}
{{- $podAnnotations = .Values.global.podAnnotations | default dict }}
{{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/bow/configmap.yaml") . | sha256sum }}
{{- with $podAnnotations }}
        {{- toYaml . | nindent 8 }}
{{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.bow.terminationGracePeriodSeconds }}
{{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
{{- range . }}
        - name: {{ . }}
{{- end }}
{{- end }}
{{- if .Values.bow.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.bow.nodeSelector | nindent 8 }}
{{- else if .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.global.nodeSelector | nindent 8 }}
{{- end }}
{{- if .Values.bow.tolerations }}
      tolerations:
        {{- toYaml .Values.bow.tolerations | nindent 8 }}
{{- else if .Values.global.tolerations }}
      tolerations:
        {{- toYaml .Values.global.tolerations | nindent 8 }}
{{- end }}
{{- if .Values.bow.affinity }}
      affinity:
        {{- toYaml .Values.bow.affinity | nindent 8 }}
{{- else if .Values.global.affinity }}
      affinity:
        {{- toYaml .Values.global.affinity | nindent 8 }}
{{- end }}
      {{- $imageTag := coalesce .Values.bow.image.tag .Values.global.image.tag .Chart.AppVersion }}
      containers:
        - name: bow
          image: "{{ .Values.bow.image.repository }}:{{ $imageTag }}"
          imagePullPolicy: {{ .Values.bow.image.pullPolicy }}
{{- with .Values.bow.command }}
          command:
            {{- toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.bow.args }}
          args:
            {{- toYaml . | nindent 12 }}
{{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "bosun.componentFullname" (dict "root" . "component" "bow") }}-env
          ports:
            - name: http
              containerPort: {{ .Values.bow.containerPort }}
              protocol: TCP
{{- with .Values.bow.probes.readiness }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.bow.probes.liveness }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.bow.probes.startup }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
{{- end }}
{{- if .Values.bow.resources }}
          resources:
            {{- toYaml .Values.bow.resources | nindent 12 }}
{{- else if .Values.global.resources }}
          resources:
            {{- toYaml .Values.global.resources | nindent 12 }}
{{- end }}
{{- end }}
