{{- if .Values.bow.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bosun.componentFullname" (dict "root" . "component" "bow") }}
  namespace: {{ include "bosun.namespace" . }}
  labels:
    {{- include "bosun.labels" . | nindent 4 }}
    app.kubernetes.io/component: bow
{{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.bow.service.type }}
  ports:
    - name: http
      port: {{ .Values.bow.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "bosun.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: bow
{{- end }}
