{{- if .Values.quak.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bosun.componentFullname" (dict "root" . "component" "quak") }}
  namespace: {{ include "bosun.namespace" . }}
  labels:
    {{- include "bosun.labels" . | nindent 4 }}
    app.kubernetes.io/component: quak
{{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.quak.service.type }}
{{- if .Values.quak.service.sessionAffinity }}
  sessionAffinity: {{ .Values.quak.service.sessionAffinity }}
{{- if eq .Values.quak.service.sessionAffinity "ClientIP" }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.quak.service.sessionAffinityTimeoutSeconds }}
{{- end }}
{{- end }}
  ports:
    - name: http
      port: {{ .Values.quak.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "bosun.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: quak
{{- end }}
