prepull:
  enabled: false
overprovisioner:
  enabled: false
storageClass:
  enabled: false
global:
  imagePullSecrets: []

bow:
  replicas: 1
  ingress:
    enabled: false

stern:
  replicas: 1
  ingress:
    enabled: false

quak:
  replicas: 1
  executorNamespace:
    create: true
    name: tasks
