{{- if .Values.bow.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bosun.componentFullname" (dict "root" . "component" "bow") }}-env
  namespace: {{ include "bosun.namespace" . }}
  labels:
    {{- include "bosun.labels" . | nindent 4 }}
    app.kubernetes.io/component: bow
{{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
data:
{{- $userEnv := .Values.bow.env | default dict }}
{{- $env := dict }}
{{- range $key, $value := $userEnv }}
{{- $_ := set $env $key $value }}
{{- end }}
{{- $sternService := include "bosun.componentFullname" (dict "root" . "component" "stern") }}
{{- $_ := set $env "BACKEND_URL" (default (printf "http://%s:%d" $sternService (int .Values.stern.service.port)) (get $userEnv "BACKEND_URL")) }}
{{- if $env }}
{{- range $key, $value := $env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- else }}
  {}
{{- end }}
{{- end }}
