{{- if .Values.postgres.enabled }}
{{- $secretName := default (printf "%s-auth" (include "bosun.componentFullname" (dict "root" . "component" "postgres"))) .Values.postgres.auth.existingSecret }}
{{- $serviceName := include "bosun.componentFullname" (dict "root" . "component" "postgres") }}
{{- if not .Values.postgres.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ include "bosun.namespace" . }}
  labels:
    {{- include "bosun.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
type: Opaque
stringData:
  {{ .Values.postgres.auth.usernameKey }}: {{ .Values.postgres.auth.username | quote }}
  {{ .Values.postgres.auth.passwordKey }}: {{ .Values.postgres.auth.password | quote }}
  {{ .Values.postgres.auth.databaseKey }}: {{ .Values.postgres.auth.database | quote }}
  {{ .Values.postgres.auth.baseUrlKey }}: {{ printf "postgresql://%s:%s@%s:%d/" .Values.postgres.auth.username .Values.postgres.auth.password $serviceName (.Values.postgres.service.port | int) | quote }}
{{- end }}
{{- end }}
