{{- if .Values.stern.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bosun.componentFullname" (dict "root" . "component" "stern") }}-env
  namespace: {{ include "bosun.namespace" . }}
  labels:
    {{- include "bosun.labels" . | nindent 4 }}
    app.kubernetes.io/component: stern
{{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
data:
{{- $userEnv := .Values.stern.env | default dict }}
{{- $env := dict }}
{{- range $key, $value := $userEnv }}
{{- $_ := set $env $key $value }}
{{- end }}
{{- $redisService := include "bosun.componentFullname" (dict "root" . "component" "redis-shared") }}
{{- $quakService := include "bosun.componentFullname" (dict "root" . "component" "quak") }}
{{- $sternService := include "bosun.componentFullname" (dict "root" . "component" "stern") }}
{{- $sternHost := printf "%s:%d" $sternService (int .Values.stern.service.port) }}
{{- $quakHost := printf "%s:%d" $quakService (int .Values.quak.service.port) }}
{{- $allowedHosts := .Values.stern.hostAuthorization.allowedHosts | default (list) }}
{{- $userAllowedHosts := get $userEnv "STERN_ALLOWED_HOSTS" | default "" }}
{{- $_ := set $env "REDIS_URL" (default (printf "redis://%s:%d" $redisService (int .Values.redis.shared.service.port)) (get $userEnv "REDIS_URL")) }}
{{- $_ := set $env "QUAK_URL" (default (printf "http://%s:%d" $quakService (int .Values.quak.service.port)) (get $userEnv "QUAK_URL")) }}
{{- $_ := set $env "ROOT_URL" (default (printf "http://%s:%d" $sternService (int .Values.stern.service.port)) (get $userEnv "ROOT_URL")) }}
{{- if or (gt (len $allowedHosts) 0) $userAllowedHosts }}
{{- $combinedAllowedHosts := list $sternHost $quakHost }}
{{- range $allowedHosts }}
{{- $combinedAllowedHosts = append $combinedAllowedHosts . }}
{{- end }}
{{- if $userAllowedHosts }}
{{- $combinedAllowedHosts = append $combinedAllowedHosts $userAllowedHosts }}
{{- end }}
{{- $_ := set $env "STERN_ALLOWED_HOSTS" (join "," $combinedAllowedHosts) }}
{{- end }}
{{- if eq .Values.scm.mode "gitlab" }}
{{- $_ := set $env "GITLAB_API_ENDPOINT" (default .Values.scm.gitlab.apiEndpoint (get $userEnv "GITLAB_API_ENDPOINT")) }}
{{- $_ := set $env "AUTHENTICATION_DISABLED" (default "true" (get $userEnv "AUTHENTICATION_DISABLED")) }}
{{- end }}
{{- if $env }}
{{- range $key, $value := $env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- else }}
  {}
{{- end }}
{{- end }}
