{{- if and .Values.stern.enabled .Values.stern.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bosun.componentFullname" (dict "root" . "component" "stern") }}
  namespace: {{ include "bosun.namespace" . }}
  labels:
    {{- include "bosun.labels" . | nindent 4 }}
    app.kubernetes.io/component: stern
{{- with .Values.stern.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
{{- if .Values.stern.ingress.className }}
  ingressClassName: {{ .Values.stern.ingress.className }}
{{- end }}
  rules:
{{- range .Values.stern.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
{{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "bosun.componentFullname" (dict "root" $ "component" "stern") }}
                port:
                  number: {{ $.Values.stern.service.port }}
{{- end }}
{{- end }}
{{- with .Values.stern.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
